# Generated by Django 5.2 on 2025-04-25 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currencies'},
        ),
    ]
