# Generated by Django 5.2 on 2025-04-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_alter_currency_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='coingecko_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
